name: lint test deploy
on: workflow_dispatch
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint
        run: npm run lint

